swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
host: localhost:8080
basePath: /
tags:
  - name: news-controller
    description: News Controller
  - name: user-controller
    description: User Controller
paths:
  /api/news/:
    get:
      tags:
        - news-controller
      summary: getNews
      operationId: getNewsUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/NewsDTO'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/news/space-flight:
    get:
      tags:
        - news-controller
      summary: externalNews
      operationId: externalNewsUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/NewsDTO'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/users/{id}:
    get:
      tags:
        - user-controller
      summary: getUser
      operationId: getUserUsingGET
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/UserDTO'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/users/{userId}/news-favorite:
    get:
      tags:
        - user-controller
      summary: findNewsFavorite
      operationId: findNewsFavoriteUsingGET
      produces:
        - '*/*'
      parameters:
        - name: userId
          in: path
          description: userId
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/NewsDTO'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/users/{userId}/news-favorite/{newsId}:
    post:
      tags:
        - user-controller
      summary: addNewsFavorite
      operationId: addNewsFavoriteUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: newsId
          in: path
          description: newsId
          required: true
          type: integer
          format: int64
        - name: userId
          in: path
          description: userId
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            type: string
            enum:
              - ACCEPTED
              - ALREADY_REPORTED
              - BAD_GATEWAY
              - BAD_REQUEST
              - BANDWIDTH_LIMIT_EXCEEDED
              - CHECKPOINT
              - CONFLICT
              - CONTINUE
              - CREATED
              - DESTINATION_LOCKED
              - EXPECTATION_FAILED
              - FAILED_DEPENDENCY
              - FORBIDDEN
              - FOUND
              - GATEWAY_TIMEOUT
              - GONE
              - HTTP_VERSION_NOT_SUPPORTED
              - IM_USED
              - INSUFFICIENT_SPACE_ON_RESOURCE
              - INSUFFICIENT_STORAGE
              - INTERNAL_SERVER_ERROR
              - I_AM_A_TEAPOT
              - LENGTH_REQUIRED
              - LOCKED
              - LOOP_DETECTED
              - METHOD_FAILURE
              - METHOD_NOT_ALLOWED
              - MOVED_PERMANENTLY
              - MOVED_TEMPORARILY
              - MULTIPLE_CHOICES
              - MULTI_STATUS
              - NETWORK_AUTHENTICATION_REQUIRED
              - NON_AUTHORITATIVE_INFORMATION
              - NOT_ACCEPTABLE
              - NOT_EXTENDED
              - NOT_FOUND
              - NOT_IMPLEMENTED
              - NOT_MODIFIED
              - NO_CONTENT
              - OK
              - PARTIAL_CONTENT
              - PAYLOAD_TOO_LARGE
              - PAYMENT_REQUIRED
              - PERMANENT_REDIRECT
              - PRECONDITION_FAILED
              - PRECONDITION_REQUIRED
              - PROCESSING
              - PROXY_AUTHENTICATION_REQUIRED
              - REQUESTED_RANGE_NOT_SATISFIABLE
              - REQUEST_ENTITY_TOO_LARGE
              - REQUEST_HEADER_FIELDS_TOO_LARGE
              - REQUEST_TIMEOUT
              - REQUEST_URI_TOO_LONG
              - RESET_CONTENT
              - SEE_OTHER
              - SERVICE_UNAVAILABLE
              - SWITCHING_PROTOCOLS
              - TEMPORARY_REDIRECT
              - TOO_EARLY
              - TOO_MANY_REQUESTS
              - UNAUTHORIZED
              - UNAVAILABLE_FOR_LEGAL_REASONS
              - UNPROCESSABLE_ENTITY
              - UNSUPPORTED_MEDIA_TYPE
              - UPGRADE_REQUIRED
              - URI_TOO_LONG
              - USE_PROXY
              - VARIANT_ALSO_NEGOTIATES
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    delete:
      tags:
        - user-controller
      summary: deleteNewsFavorite
      operationId: deleteNewsFavoriteUsingDELETE
      produces:
        - '*/*'
      parameters:
        - name: newsId
          in: path
          description: newsId
          required: true
          type: integer
          format: int64
        - name: userId
          in: path
          description: userId
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            type: string
            enum:
              - ACCEPTED
              - ALREADY_REPORTED
              - BAD_GATEWAY
              - BAD_REQUEST
              - BANDWIDTH_LIMIT_EXCEEDED
              - CHECKPOINT
              - CONFLICT
              - CONTINUE
              - CREATED
              - DESTINATION_LOCKED
              - EXPECTATION_FAILED
              - FAILED_DEPENDENCY
              - FORBIDDEN
              - FOUND
              - GATEWAY_TIMEOUT
              - GONE
              - HTTP_VERSION_NOT_SUPPORTED
              - IM_USED
              - INSUFFICIENT_SPACE_ON_RESOURCE
              - INSUFFICIENT_STORAGE
              - INTERNAL_SERVER_ERROR
              - I_AM_A_TEAPOT
              - LENGTH_REQUIRED
              - LOCKED
              - LOOP_DETECTED
              - METHOD_FAILURE
              - METHOD_NOT_ALLOWED
              - MOVED_PERMANENTLY
              - MOVED_TEMPORARILY
              - MULTIPLE_CHOICES
              - MULTI_STATUS
              - NETWORK_AUTHENTICATION_REQUIRED
              - NON_AUTHORITATIVE_INFORMATION
              - NOT_ACCEPTABLE
              - NOT_EXTENDED
              - NOT_FOUND
              - NOT_IMPLEMENTED
              - NOT_MODIFIED
              - NO_CONTENT
              - OK
              - PARTIAL_CONTENT
              - PAYLOAD_TOO_LARGE
              - PAYMENT_REQUIRED
              - PERMANENT_REDIRECT
              - PRECONDITION_FAILED
              - PRECONDITION_REQUIRED
              - PROCESSING
              - PROXY_AUTHENTICATION_REQUIRED
              - REQUESTED_RANGE_NOT_SATISFIABLE
              - REQUEST_ENTITY_TOO_LARGE
              - REQUEST_HEADER_FIELDS_TOO_LARGE
              - REQUEST_TIMEOUT
              - REQUEST_URI_TOO_LONG
              - RESET_CONTENT
              - SEE_OTHER
              - SERVICE_UNAVAILABLE
              - SWITCHING_PROTOCOLS
              - TEMPORARY_REDIRECT
              - TOO_EARLY
              - TOO_MANY_REQUESTS
              - UNAUTHORIZED
              - UNAVAILABLE_FOR_LEGAL_REASONS
              - UNPROCESSABLE_ENTITY
              - UNSUPPORTED_MEDIA_TYPE
              - UPGRADE_REQUIRED
              - URI_TOO_LONG
              - USE_PROXY
              - VARIANT_ALSO_NEGOTIATES
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
definitions:
  NewsDTO:
    type: object
    properties:
      formatted_published_at:
        type: string
      id:
        type: integer
        format: int64
      image_url:
        type: string
      news_site:
        type: string
      published:
        type: boolean
      published_at:
        type: string
        format: date
      summary:
        type: string
      title:
        type: string
      updated_at:
        type: string
        format: date
      url:
        type: string
    title: NewsDTO
  UserDTO:
    type: object
    properties:
      birth_date:
        type: string
        format: date
      creation_date:
        type: string
        format: date
      favorite_news:
        type: array
        items:
          $ref: '#/definitions/NewsDTO'
      id:
        type: integer
        format: int64
      is_active:
        type: boolean
      password:
        type: string
      username:
        type: string
    title: UserDTO
